version: '3.7'


services:

  sage-api:
    image: sagecontinuum/ses-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      TESTING_NOAUTH: ${TESTING_NOAUTH}
      tokenInfoEndpoint: ${tokenInfoEndpoint}
      tokenInfoUser: ${tokenInfoUser} 
      tokenInfoPassword: ${tokenInfoPassword}
